" === For development only

set nocompatible
set mouse=a
let &runtimepath.=','.escape(expand('<sfile>:p:h'), '\,').'/..'


" === For testing FZF support

call plug#begin('~/.local/share/nvim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()

function! s:bugg_log_details(lines)
  call g:BuggLogDetails(a:lines)
endfunction
command! -bang FzfBuggLog call fzf#run({ 'source': getbufline(bufnr('bugg_buffer_log_history'), 1, "$"), 'sink*': function('s:bugg_log_details'), 'window': { 'width': 0.9, 'height': 0.6 }})


" === To be executed as part of the plugin
highlight def link BuggBreakpointLine Search
highlight def link BuggBreakpointNum Search
highlight def link BuggBreakpointText ErrorMsg

sign define BuggBreakpoint linehl=BuggBreakpointLine numhl=BuggBreakpointNum texthl=BuggBreakpointText text=*>
sign define BuggBreakpointCondition linehl=BuggBreakpointLine numhl=BuggBreakpointNum texthl=BuggBreakpointText text=?>


" === An optional default set of bindings

nmap gbb :BuggToggleBreakpoint<cr>
nmap gbB :BuggSetBreakpoint |" Leaves the cursor in command line mode for condition entry
nmap gbl :FzfBuggLog<cr>
nmap gbs :BuggStart<cr>
nmap gbS :BuggStop<cr>


" === Customisations a user of the plugin can make in their vimrc

let g:bugg_xdebug_port = 9000
let g:bugg_max_log_history = 1000

