" === For development only

set nocompatible
set mouse=a
let &runtimepath.=','.escape(expand('<sfile>:p:h'), '\,').'/..'


" === For testing FZF support

call plug#begin('~/.local/share/nvim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()


" === Options users can put in their vimrc

let g:bugg_enable_default_bindings = 1

